name: application
description: "Base flutter application"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  shared_preferences: ^2.3.1
  flutter_svg: ^2.0.10+1
  advertising_id: ^2.6.0
  carousel_slider: ^5.0.0
  core_amplitude:
    git:
      url: git@railroad.git.emehanika.com:flutter/core/core_amplitude.git
      tag: 1.0.0
  equatable: ^2.0.5
  loading_indicator: ^3.1.1
  share_plus: ^10.0.3
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_xlider: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/recipe.json
    - assets/json/challenge.json

fonts:
  - family: poppins
    fonts:
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/poppins-light.ttf
        weight: 300